import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'
import { sendEmail } from '@/lib/mail'
import { logger } from '@/lib/logger'
import Groq from 'groq-sdk'

// Initialize Groq
const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
})

// Function to get a fresh AI message
async function getDailyInsight() {
  try {
    const completion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are an elite productivity coach. Output ONLY plain text."
        },
        {
          role: "user",
          content: "Write a single, punchy, 2-sentence motivational command for a high-performer starting their day. No emojis. No hashtags. Example: 'Discipline is the bridge between goals and accomplishment. Cross it today.'"
        }
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.8,
      max_tokens: 60,
    });

    return completion.choices[0]?.message?.content || "Consistency is your competitive advantage. Keep your streak alive."
  } catch (error) {
    console.error('Groq AI Failed:', error)
    return "Consistency is your competitive advantage. Keep your streak alive." // Fallback if AI fails
  }
}

export async function GET(request: Request) {
  // 1. Security Check
  const authHeader = request.headers.get('authorization')
  if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    // 2. Get Time & Greeting
    const date = new Date()
    const options = { timeZone: 'Asia/Kolkata', hour12: false, hour: 'numeric' }
    // @ts-ignore
    const currentHour = parseInt(date.toLocaleTimeString('en-US', options))
    
    let greeting = 'Good Morning'
    if (currentHour >= 12 && currentHour < 17) greeting = 'Good Afternoon'
    else if (currentHour >= 17) greeting = 'Good Evening'

    // 3. GENERATE AI MESSAGE (New Step)
    // We fetch this ONCE per day, then send it to everyone (saves API credits & time)
    const aiMessage = await getDailyInsight()
    logger.info(`Daily Insight Generated: "${aiMessage}"`)

    // 4. Admin Client Setup
    const supabaseAdmin = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    )

    // 5. Fetch Users
    const { data: users, error } = await supabaseAdmin
      .from('users')
      .select('email, display_name')
      .eq('deep_work_protection', false)

    if (error) throw error
    if (!users || users.length === 0) return NextResponse.json({ message: 'No users found' })

    // 6. Send Emails
    let sentCount = 0
    for (const user of users) {
      if (user.email) {
        const userName = user.display_name || 'Operator'

        await sendEmail(
          user.email,
          `AXON: ${greeting} Protocol Briefing`,
          `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #111;">
              <h2 style="margin-bottom: 10px;">${greeting}, ${userName}</h2>
              
              <p style="font-size: 16px; color: #444; margin-bottom: 24px; line-height: 1.5; border-left: 3px solid #000; padding-left: 15px; font-style: italic;">
                "${aiMessage}"
              </p>
              
              <a href="https://axonhabitsystem.vercel.app/dashboard" 
                 style="background: #000; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 14px; display: inline-block;">
                 Log Progress →
              </a>
              
              <p style="margin-top: 30px; font-size: 12px; color: #888;">
                Daily insight generated by AXON AI Neural Core.
              </p>
            </div>
          `
        )
        sentCount++
      }
    }

    return NextResponse.json({ success: true, emails_sent: sentCount, message: aiMessage })

  } catch (error: any) {
    console.error('Cron Job Failed:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}